Add GitHub Steampipe CLI, FDW, SDK, Docs Repository Checks benchmark
cbruno10/steampipe-mod-github-tracker pull request #4
Opened 2023-09-26 13:39 UTC by misraved

2023-09-26 22:42 UTC, cbruno10 requested changes
@misraved Please see comments, thanks!

2023-09-26 22:42 UTC, cbruno10 commented on controls/repository.sp
> +    control.repository_mod_has_mandatory_topics,
Did these controls throttle at all, or seem to slow down the overall execution (since they use v3 API hydrate data)?

2023-09-26 22:42 UTC, cbruno10 commented on controls/repository.sp
> +    control.repository_mod_uses_monotonic_versioning,
Can you please leave this control commented out for now? I think we need a better approach than scanning all releases, maybe we should take the last 5 releases, but can make that change later

2023-09-26 22:42 UTC, cbruno10 commented on controls/repository.sp
> +      query ='repo:turbot/steampipe repo:turbot/steampipe-plugin-sdk repo:turbot/steampipe-docs repo:turbot/steampipe-postgres-fdw is:public archived:false'
Can you please add a local in `vars.sp` to store this query? This makes it easy to update in one place

2023-09-26 22:42 UTC, cbruno10 commented on controls/repository.sp
> +    benchmark.repository_steampipe_cli_fdw_sdk_docs_checks
```suggestion
    benchmark.repository_steampipe_core_checks
```

Not sure `core` is the right name, but I think it's shorter and still applies to all of the repos in scope

2023-09-26 22:42 UTC, cbruno10 commented on controls/repository.sp
> +  title = "Steampipe CLI, FDW, SDK, Docs repositories have a standard description"
```suggestion
  title = "Steampipe core repositories have a standard description"
```

2023-09-27 12:56 UTC, misraved commented on controls/repository.sp
> +    control.repository_mod_has_mandatory_topics,
@cbruno10 I did not see any kind of slowness while running the queries. But happy to do more testing on this one 👍.

2023-09-27 18:27 UTC, cbruno10 approved these changes

2023-09-27 18:27 UTC, merged